### ISSUE TITLE
Can't use this code.

### ISSUE THREAD

**Issue by Yabish** [phatnguyenuit/HackerRank-Angular-Basic#1]
In `temperature-converter` code ReactiveFormsModule is used in `app.module.ts `file, which is a non-editable (Read-only) file.

**Comment by phatnguyenuit** [comment]
Hi @Yabish,
oh, you can use `property binding` only.
or use formControl name.

**Comment by Yabish** [comment]
Yeah I did. But in this case this code didn't work.
